added hidden page
flaviostutz/onboarding-web-students pull request #2
Opened 2023-02-09 08:38 UTC by nielsmijnster

2023-02-09 10:32 UTC, flaviostutz requested changes
Pls format the code

2023-02-09 10:32 UTC, flaviostutz commented on html/hidden.html
> +<html style="height: 100%;"><head><meta name="viewport" content="width=device-width, minimum-scale=0.1"><title>aboutme.png (992×1058)</title></head><body style="margin: 0px; background: #0e0e0e; heig
Pls format this HTML code. You can use VSCode plugins for that

2023-02-10 07:35 UTC, nielsmijnster commented on html/hidden.html
> +<html style="height: 100%;"><head><meta name="viewport" content="width=device-width, minimum-scale=0.1"><title>aboutme.png (992×1058)</title></head><body style="margin: 0px; background: #0e0e0e; heig
aah nice, yeah i just used prettier, thanks for the remark!

2023-02-10 07:58 UTC, flaviostutz approved these changes
Nice!

2023-04-05 22:14 UTC, flaviostutz approved these changes
Very nice, man!!!

2023-04-05 22:15 UTC, merged